server:
  port: 8080
spring:
  application:
    name: mybatis
    abbr: MYBATIS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ztkj.com:13320/car?allowMultiQueries=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: car
    password: car

mybatis:
  mapper-locations: classpath:com/example/ztkj/mybatis/mapper/*Mapper.xml
  type-aliases-package: com.example.ztkj.mybatis.model

logging:
  level:
    ROOT: warn
    org.springframework: info
    org.springframework.web.servlet.view: info
    org.springframework.web.servlet.mvc: info
    io.undertow.request: info
    com.example: debug
    com.github.pagehelper: TRACE
    com.zaxxer.hikari: TRACE
  file:
    name: /app/logs/${spring.application.name} # 日志文件保存路径
